README.md
=> feat: Add logo

README.md
=> fix: Fix logo on dark theme

README.md
=> Add stackblitz demo

README.md
=> chore: Polish README.md

examples/nextjs/README.md, website/blog/2022-04-21-introduce-jest-preview-docs/index.md, website/docs/examples/next-babel.md, website/docs/examples/next-rust.md, website/package-lock.json
=> Nextjs website

config/jest/setupTests.js, jest.config.js
=> Fix scss at /demo folder

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/improvement.md
=> feat: Add improvement issue template

website/docs/getting-started/intro.md
- Update the intro markdown to fix the grammar.
=> docs: Update intro.md

.gitignore, CHANGELOG.md, package-lock.json, package.json
=> Fix space in folder

website/package-lock.json, website/package.json
=> chore: Update docusaurus to newest version

README.md
~~- [ ] Wait a few days for `weeekly` data is available, then change to `weekly` (then `monthly` later)~~
- https://github.com/bestofjs/bestofjs-webui/issues/79
=> feat: add Best of JS badge

README.md
=> feat: add Star History

README.md, website/src/components/Sponsors/index.tsx, website/src/components/Sponsors/styles.module.css, website/src/pages/index.tsx
Monthly sponsor from [0xKiraa](https://opencollective.com/0xkiraa)
=> chore: add webuild sponsor

README.md
=> feat: Add mention in awesome badge

.github/PULL_REQUEST_TEMPLATE.md, README.md, website/docs/others/support.md
=> docs: Add support channels

README.md, cli/server/previewServer.js, website/docs/getting-started/intro.md
This PR is to update the docs and Jest Preview Dashboard based on feedback on this article https://dev.to/mbarzeev/giving-jest-preview-a-spin-24b9 cc: @mbarzeev
=> feat: Improve the log in Jest Preview Dashboard and polish docs

cli/clearCache.js, cli/configCra.js, cli/index.js, examples/create-react-app/package.json, package.json
=> feat: Update postinstall + add clear-cache CLI

website/blog/2022-06-25-jsparty/index.mdx
=> feat: add transcript for jsparty

website/blog/2022-04-21-introduce-jest-preview-docs/index.md, website/blog/2022-04-23-sass-support/index.md, website/blog/2022-04-25-nextjs-support/index.md, website/blog/2022-05-03-automatic-mode/index.md, website/blog/2022-05-23-first-class-support-cra/index.md, website/blog/2022-06-11-deprecate-externalCss/index.md, website/blog/2022-06-25-jsparty/index.mdx, website/docusaurus.config.js
Improve [the docs](https://www.jest-preview.com/) and add [Feedback link](https://forms.gle/PJFH5oEzi7gsb7Ac6)
=> Docs improvement

README.md
This change harmonizes the spelling of Next.js in the README.
=> docs: Harmonize Next.js spelling

CHANGELOG.md, cli/server/previewServer.js, package-lock.json, package.json, src/preview.ts
- Simplify preview logic.
- #184
=> Simplify preview logic

CHANGELOG.md, cli/configCra.js, examples/create-react-app/jest.config.js, src/transform.ts, website/blog/2022-05-23-first-class-support-cra/index.md, website/docs/advanced-guides/code-transform.md, website/docs/getting-started/installation.md
Merge file and fileCRA transforms
- #182
=> chore: Merge file and fileCRA transformations

.github/workflows/cypress.yml, .github/workflows/test.yml, docs-e2e-testing/cypress.config.js
=> feat: record cypress results

website/docs/getting-started/intro.md
Fixed broken link introduced with previous PR
- #207 
- Fixed broken link
=> [207] fixed broken link and change wording

examples/create-react-app/jest.config.js, examples/jest-24/jest.config.js, examples/jest-28/jest.config.js, examples/remix/jest.config.js, examples/svelte/jest.config.js, examples/vite-react/jest.config.js, examples/vue/jest.config.js, jest.config.js, website/blog/2022-05-23-first-class-support-cra/index.md
=> chore: add type hint for jest.config.js

README.md
=> feat: Add deploysentinel.com as bronze sponsor

website/src/components/Sponsors/index.tsx, website/src/components/Sponsors/styles.module.css
=> feat: add deploysential to documentation site

website/package-lock.json, website/package.json
=> feat: Update docusaurus to version 2.0.1

website/blog/2022-06-25-jsparty/index.mdx
=> Fix typo in podcast blog post

website/src/components/Carbon/index.tsx
=> chore: fix typo in Carbon/index.tsx

CHANGELOG.md, README.md, examples/svelte/README.md, package.json, website/docs/advanced-guides/code-transform.md, website/docs/api/jestPreviewConfigure.md, website/docs/examples/svelte.md, website/docs/getting-started/installation.md, website/docs/getting-started/intro.md, website/docs/getting-started/usage.md
=> Polish readme and docs

examples/vite-react/src/__tests__/global-style-components.test.tsx, website/docs/others/faq.md
Add workaround for global style when using `style-components`
=> chore: add workaround for styled-components

website/i18n/zh-CN/code.json, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/intro.md
=> docs(i18n/zh-cn): update

CONTRIBUTING.md, TRANSLATION.md, website/docusaurus.config.js
=> Add translation guide

package.json, website/docusaurus.config.js, website/package.json
- Deploy Chinese docs at `cn.jest-preview.com`
#281
=> Deploy Chinese docs at `cn.jest-preview.com`

website/docs/getting-started/intro.md, website/docusaurus.config.js, website/i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/intro.md
Fix Chinese language typo and add a split line
=> Fix i18n dropdown typo and a wrong link

website/package-lock.json, website/package.json
=> chore: Update docusaurus

website/package-lock.json, website/package.json
=> chore: re-generate package-lock for website

.github/workflows/cypress.yml, .github/workflows/jest-preview-ecosystem-ci.yml, .github/workflows/test.yml
=> 🧹 chore: use actions/checkout@v3

README.md, website/src/components/Sponsors/index.tsx
=> chore: update sponsors
