nvh95/jest-preview

.gitignore
config/jest/cssTransform.js
config/jest/fileTransform.js
package-lock.json
package.json
src/transform.ts

- The reason is the last commit of `postcss-modules-sync` is from Jan 2017. I think it might not cover all the use cases today. `postcss-modules` is kind of an official solution to process CSS Modules. (however, I still love to have synchronous support for that)
- We used to have to use `postcss-modules-sync` since we've not yet discovered a way to make it work with asynchronous postcss plugin. Now we can deal with this with Singleton Design Pattern. So just use the official solution

Use `postcss-modules` to process CSS Modules instead of `postcss-modules-sync`

---

demo/__tests__/Translate.test.tsx
demo/components/Translate.tsx
server/previewServer.js

- Add `<meta charset="UTF-8">` to html template to be able to render non English characters on Jest Preview Dashboard.
- Add `<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover">` to support responsive design on Jest Preview Dashboard.
I added new component `Translate` and add test to it.

feat: support non-english characters and responsive design

---

README.md
server/previewServer.js

chore: Remind users to clearCache after config

---

README.md
demo/App.tsx
demo/__tests__/App.test.tsx
demo/__tests__/style.test.tsx
examples/nextjs/pages/index.tsx
package-lock.json
package.json
website/docs/getting-started/features.md

Already support Emotion + Add note about `styled-jsx` and `Stiches`

---

CHANGELOG.md
package-lock.json
package.json
src/configure.ts

Fix global sass on windows

---

.github/workflows/no-response.yml

Auto close a issue with `needs-response` tag after 10 days

---

cli/index.js
cli/server/previewServer.js
package-lock.json
package.json

About @duong-le's considerations in https://github.com/nvh95/jest-preview/issues/109#issuecomment-1139927283
1. `update-notifier` already support [3 ways](https://github.com/yeoman/update-notifier#user-settings) to disable the notification, I don't think that we need more than that.
3. As the package author said: `This behavior is intentional` in https://github.com/yeoman/update-notifier/issues/209#issuecomment-872302890, the choice is up to us.
5. `update-notifier` has a helpful [distTag](https://github.com/yeoman/update-notifier#disttag) support so we can take advantage of it to notify in multiple distribution types.

Feat: notify users whenever an update available

---

docs-e2e-testing/cypress.config.ts
docs-e2e-testing/e2e/jest-preview.cy.js
docs-e2e-testing/fixtures/example.json
docs-e2e-testing/package-lock.json
docs-e2e-testing/package.json
docs-e2e-testing/support/commands.ts
docs-e2e-testing/support/e2e.ts

Cypress test

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/example_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement.md
.github/PULL_REQUEST_TEMPLATE.md

This PR contains no code. It updates the templates when people come to open a new issue or a pull request. We want them to feel as welcome as possible.

chore: Update .github templates

---

README.md
website/blog/2022-04-21-introduce-jest-preview-docs/index.md
website/docs/getting-started/features.md
website/docs/getting-started/installation.md
website/docs/others/faq.md

People forgot to configure **external** CSS in `setupTest.js`/ `jest.setup.js`. We rename **external CSS** => **global CSS**. So users get familiar with it more. And hope they don't forget to configure **global CSS**.

docs: rename external CSS => global CSS for easier understanding

---

.github/workflows/cypress.yml

feat: Run cypress on documentation site periodically

---

docs-e2e-testing/package.json

- After merging PR #192, the workflow still failed because the e2e config file uses the es module, which is not supported in workflow environment
- #181

fix: Support es module for e2e test

---

CHANGELOG.md
cli/server/previewServer.js
package-lock.json
package.json
website/docs/others/faq.md

- Preview page doesn't automatically reload after running tests
- Possible root cause: https://github.com/nvh95/jest-preview/pull/199#issuecomment-1186088862
- #138 
- Move "clear cache" code out of `server.listen` callback
- Always write `index.html` to make sure it's always existed
- Do not generate "blank page" on demand (`app.use('/')`), instead, write to disk at **2.**
*We also tried another approach here (generate a new file name for index.html each time the server starts), we can keep this as a reference https://github.com/nvh95/jest-preview/pull/199*

Fix issue not reload on Linux by always read html from `index.html`

---

examples/jquery/README.md
examples/jquery/jest.config.js
examples/jquery/package.json
examples/jquery/src/app.js
examples/jquery/src/app.test.js
examples/jquery/src/index.html
examples/jquery/src/setupTests.js

example: add jquery example

---

website/docs/others/faq.md

`jestPreviewConfigure` is not the way to configure global CSS. `setupTests.js` is correct place.

docs: proper description for configuring global CSS

---

website/docs/getting-started/installation.md

The step count of step 6 was marked as a duplicate step 5.
I followed the installation guide and noticed two step 5s.
- N/A

docs: correct installation step count

---

examples/nextjs/README.md

Previous link went to a 404 page in the nextjs example readme
- None

Fix link typo in nextjs example README

---

jest.config.js
package.json
pnpm-lock.yaml
src/__tests__/230/base.css
src/__tests__/230/components.css
src/__tests__/230/index.css
src/__tests__/230/index.html
src/__tests__/230/index.test.ts
src/__tests__/230/postcss.config.cjs
src/__tests__/230/tailwind.config.cjs
src/__tests__/230/utils.css
src/transform.ts

Inline `@import` syntax
- #230

Inline import

---

src/configure.ts
website/blog/2022-06-11-deprecate-externalCss/index.md

- Do not merge it yet. Leave it for `0.3.1`

Deprecate externalCss in 0.3.1

---

CHANGELOG.md
cli/server/ws-client.js
package.json

fix: Use hostname instead of localhost

---

package.json
pnpm-lock.yaml

🧹 chore: update update-notifier to solve dependbot issue

---

website/docusaurus.config.js
website/i18n/vi-VN/code.json
website/i18n/vi-VN/docusaurus-plugin-content-blog/options.json
website/i18n/vi-VN/docusaurus-plugin-content-docs/current.json
website/i18n/vi-VN/docusaurus-theme-classic/footer.json
website/i18n/vi-VN/docusaurus-theme-classic/navbar.json
website/i18n/zh-CN/code.json
website/i18n/zh-CN/docusaurus-plugin-content-blog/options.json
website/i18n/zh-CN/docusaurus-plugin-content-docs/current.json
website/i18n/zh-CN/docusaurus-plugin-content-docs/current/getting-started/intro.md
website/i18n/zh-CN/docusaurus-theme-classic/footer.json
website/i18n/zh-CN/docusaurus-theme-classic/navbar.json
website/src/components/HomepageFeatures/index.tsx
website/src/components/Sponsors/index.tsx
website/src/pages/index.tsx

Initialize i18n for docusaurus docs. Add a little bit Chinese translation (for homepage and Introduction docs).
~~The SVG (or all static files) cannot be loaded in i18n dev mode~~
Oh it works fine on production. That's good xD
https://github.com/jsun969/jest-preview/blob/c64240c4801844663d84fc637a4d71bf0067d631/website/src/components/HomepageFeatures/index.tsx#L12
Modify `/website/i18n/vi-VN/code.json` Line2-Line64 (where id start with `home.`)
Modify files in `/website/i18n/vi-VN/docusaurus-theme-classic`
Modify `/website/i18n/vi-VN/docusaurus-plugin-content-docs/current.json` for directory  
Then see [i18n - Tutorial | Docusaurus #translate-markdown-files](https://docusaurus.io/docs/i18n/tutorial#translate-markdown-files)
The `tagline` in docusaurus config is no longer used for homepage …

docs(website): initialize i18n

---

src/cli/server/previewServer.ts

This allows `jest-preview` to be used in GitHub Codespaces and probably fixes other problems.
The preview server was not setting the content type header in the response.
Somehow this does not cause any problems when running in `localhost`, but it
seems like it prevents the preview from being rendered in GitHub Codespaces
environments, becuase the page gets rendered as a text file instead of html
- #

fix: add content type to preview server

---

src/cli/index.ts

Potential solution for the open #276 🐛
When trying to use the latest prerelease version that has update-notifier@6 installed I get the following error:
```
/jest-preview/dist/cli/index.js:5
var updateNotifier = require('update-notifier');
^
Error [ERR_REQUIRE_ESM]: require() of ES Module ...
```
Inspiration comes from the Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) section's choice num. 2 of the [update-notifier@6.0.0](https://github.com/yeoman/update-notifier/releases/tag/v6.0.0) release.
> 2. If the package is used in an async context, you could use [await import(…)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) from CommonJS instead of require(…).
- Faked an older version:
- Created …

Use update-notifier lib with dynamic import
